### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by kiriring** [TomClabault/HIPRT-Path-Tracer#1]
When executed, the following error appears

0(52) : error C7616: global variable gl_FragColor is removed after version 420

**Comment by TomClabault** [comment]
This will be fixed the next time I push (big dependencies changes going on so some the project is still broken locally, I'm not pushing right now), thanks for the report!

**Comment by TomClabault** [comment]
Hi @kiriring ,

This issue should be fixed now. Could you let me know if you're still experiencing it?
