### ISSUE TITLE
png save hangs up renderer

### ISSUE THREAD

**Issue by tigrazone** [TomClabault/HIPRT-Path-Tracer#9]
after push button "Save viewport to PNG" file saved but renderer hangs up

**Comment by TomClabault** [comment]
Hi @tigrazone !

What do you mean by "hangs up"?

The application becomes completely irresponsive and frozen?

Are there any ERROR/WARNING logs in the console?

**Comment by tigrazone** [comment]
[INFO] Screenshot written to "11.03.2024.15.59.02 - 256sp @ 1279x699 - 52.9556s.png"
[ERR ] ---------------
Debug message (131154): Pixel-path performance warning: Pixel transfer is synchronized with 3D rendering.
Source: API
Type: Performance
Severity: medium

hangs up is application not respond keyboard and mouse and not rendering.

I works on Windows 10 with NVidia 1050

**Comment by TomClabault** [comment]
Okay now I recognize this OpenGL warning. I fixed it on another branch already.

I just pushed a quick fix on `main`. Could please pull and tell me if the app still hangs when taking a screenshot?

**Comment by tigrazone** [comment]
hangup is gone with new commits. thank you for solve issue
